<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_alter.
 */
function search_api_solr_legacy_form_search_api_server_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // We need to restrict by form ID here because this function is also called
  // via hook_form_BASE_FORM_ID_alter (which is wrong, e.g. in the case of the
  // form ID search_api_field_config).
  if (
    in_array($form_id, ['search_api_server_form', 'search_api_server_edit_form']) &&
    isset($form['backend_config']['connector_config']['workarounds']['solr_version']['#options'])
  ) {
    $versions = $form['backend_config']['connector_config']['workarounds']['solr_version']['#options'] + [
      '3.6' => '3.x',
      '4.5' => '4.x',
      '5' => '5.x',
    ];
    ksort($versions);
    $form['backend_config']['connector_config']['workarounds']['solr_version']['#options'] = $versions;
  }
}

/**
 *
 */
function search_api_solr_legacy_search_api_solr_configset_template_mapping_alter(&$solr_configset_template_mapping) {
  $template_path = drupal_get_path('module', 'search_api_solr_legacy') . '/solr-conf-templates/';

  $solr_configset_template_mapping += [
    '3.x' => $template_path . '3.x',
    '4.x' => $template_path . '4.x',
    '5.x' => $template_path . '5.x',
  ];
}

/**
 * Alter the newly assembled Solr configuration files.
 *
 * @param string[] $files
 *   Array of config files keyed by file names.
 * @param string $lucene_match_version
 *   Lucene (Solr) minor version string.
 * @param string $server_id
 *   Optional Search API server id. Will be set in most cases but might be
 *   empty when the config generation is triggered via UI or drush.
 */
function search_api_solr_legacy_search_api_solr_config_files_alter(array &$files, string $lucene_match_version, string $server_id = '') {
  if (version_compare($lucene_match_version, '4', '<')) {
    if (isset($files['solrconfig.xml'])) {
      $files['solrconfig.xml'] = str_replace('SEARCH_API_SOLR_SOLRCONFIG_INDEX', $files['solrconfig_index.xml'] ?? '', $files['solrconfig.xml']);
      $files['solrconfig.xml'] = str_replace('SEARCH_API_SOLR_SOLRCONFIG_EXTRA', $files['solrconfig_extra.xml'] ?? '', $files['solrconfig.xml']);
      unset($files['solrconfig_index.xml']);
      unset($files['solrconfig_extra.xml']);
    }
    if (isset($files['schema.xml'])) {
      $files['schema.xml'] = str_replace('SEARCH_API_SOLR_SCHEMA_EXTRA_FIELDS', $files['schema_extra_fields.xml'] ?? '', $files['schema.xml']);
      $files['schema.xml'] = str_replace('SEARCH_API_SOLR_SCHEMA_EXTRA_TYPES', $files['schema_extra_types.xml'] ?? '', $files['schema.xml']);
      unset($files['schema_extra_types.xml']);
      unset($files['schema_extra_fields.xml']);
    }
  }
}

